"""Strategy code generator using LLM."""

import ast
import re
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from loguru import logger

from quantsys.agent.llm_client import LLMClient
from quantsys.config import Settings


STRATEGY_TEMPLATE = '''"""{description}

Generated by QuantSys Agent on {timestamp}
"""

from typing import Any, Dict

from quantsys.backtest.events import BarEvent
from quantsys.strategy.base import BaseStrategy


class {class_name}(BaseStrategy):
    """{description}"""

    name = "{class_name}"
    params = {params}

    def __init__(self, params: Dict[str, Any] = None) -> None:
        """Initialize strategy."""
        super().__init__(params)
        {init_code}

    def on_start(self, context: Dict[str, Any]) -> None:
        """Initialize on backtest start."""
        {on_start_code}

    def on_bar(self, bar: BarEvent) -> Dict[str, Any]:
        """Process bar and generate signal."""
        {on_bar_code}
'''


class StrategyGenerator:
    """Generate strategy code from natural language description."""

    def __init__(self, settings: Optional[Settings] = None) -> None:
        """Initialize generator."""
        from quantsys.config import get_settings

        self.settings = settings or get_settings()
        self.llm = LLMClient(self.settings)

    def generate(
        self,
        description: str,
        strategy_type: str = "momentum",
        name: Optional[str] = None,
        factor_ids: Optional[List[str]] = None,
    ) -> Path:
        """Generate strategy from description.

        Args:
            description: Strategy logic description
            strategy_type: Strategy type (momentum, mean_reversion, breakout)
            name: Strategy name (auto-generated if not provided)
            factor_ids: Optional list of factor IDs for factor-based strategies

        Returns:
            Path to generated strategy file
        """
        if not self.llm.is_available():
            raise RuntimeError("LLM not available. Set ANTHROPIC_API_KEY to generate strategies.")

        # Generate class name
        if name is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            name = f"generated_{strategy_type}_{timestamp}"

        class_name = self._to_class_name(name)

        # Generate code using LLM
        code = self._generate_with_llm(description, class_name, strategy_type, factor_ids)

        # Validate syntax
        if not self._validate_syntax(code):
            raise ValueError("Generated code has syntax errors")

        # Save to file
        output_dir = Path("quantsys/strategy/generated")
        output_dir.mkdir(parents=True, exist_ok=True)

        file_path = output_dir / f"{name}.py"
        file_path.write_text(code, encoding="utf-8")

        logger.info(f"Generated strategy saved to {file_path}")
        return file_path

    def _generate_with_llm(
        self,
        description: str,
        class_name: str,
        strategy_type: str,
        factor_ids: Optional[List[str]] = None,
    ) -> str:
        """Generate code using LLM."""
        prompt = f"""Generate a Python trading strategy based on the following description.

Description: {description}
Strategy Type: {strategy_type}
Class Name: {class_name}

The strategy must:
1. Inherit from BaseStrategy
2. Implement on_bar() method returning {{'action': 'BUY'|'SELL'|'HOLD', 'weight': float}}
3. Include appropriate parameters in params dict
4. Use type hints
5. Include docstrings

Example structure:
```python
from typing import Any, Dict
from quantsys.backtest.events import BarEvent
from quantsys.strategy.base import BaseStrategy

class {class_name}(BaseStrategy):
    name = "{class_name}"
    params = {{"period": 20}}

    def __init__(self, params: Dict[str, Any] = None) -> None:
        super().__init__(params)
        # Initialize indicators

    def on_bar(self, bar: BarEvent) -> Dict[str, Any]:
        # Strategy logic
        return {{"action": "HOLD"}}
```

Generate only the Python code, no explanations."""

        if factor_ids:
            from quantsys.factor.registry import FactorRegistry

            registry = FactorRegistry()
            registry.discover()
            factor_context = registry.get_detail(factor_ids)

            prompt += f"""

IMPORTANT: This strategy uses pre-computed factors from the QuantSys factor library.
The strategy class MUST declare: required_factors = {factor_ids}
In on_bar(), use self._get_factor(bar, "FACTOR_ID") to get the pre-computed factor value.
_get_factor returns None if data is unavailable — always check for None.

Factor definitions:
{factor_context}
"""

        messages = [{"role": "user", "content": prompt}]

        response = self.llm.chat(messages, max_tokens=2000, temperature=0.7)

        # Extract code from markdown if present
        code = self._extract_code(response)

        return code

    def _extract_code(self, text: str) -> str:
        """Extract code from markdown code blocks."""
        # Try to extract from ```python blocks
        match = re.search(r"```python\n(.*?)\n```", text, re.DOTALL)
        if match:
            return match.group(1)

        # Try any code block
        match = re.search(r"```\n(.*?)\n```", text, re.DOTALL)
        if match:
            return match.group(1)

        # Return as-is if no code blocks
        return text.strip()

    def _validate_syntax(self, code: str) -> bool:
        """Validate Python syntax."""
        try:
            ast.parse(code)
            return True
        except SyntaxError as e:
            logger.error(f"Syntax error in generated code: {e}")
            return False

    def _to_class_name(self, name: str) -> str:
        """Convert name to valid class name."""
        # Remove non-alphanumeric characters
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        # Ensure starts with letter
        if name[0].isdigit():
            name = "Strategy_" + name
        # Convert to CamelCase
        parts = name.split("_")
        return "".join(part.capitalize() for part in parts if part)
